#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /
  controller: App\Controller\MainController::login

register:
  path: /register
  controller: App\Controller\MainController::register

home:
  path: /home
  controller: App\Controller\MainController::home

top10:
  path: /top10
  controller: App\Controller\MainController::top10

users:
  path: /users
  controller: App\Controller\MainController::users

add:
  path: /add
  controller: App\Controller\MainController::add