home:
  path: /home
  controller: App\Controller\HomeController::index

top10:
  path: /top10
  controller: App\Controller\TOP10Controller::index

user:
  path: /users
  controller: App\Controller\UserController::index

add:
  path: /add
  controller: App\Controller\AddController::index

