home:
  path: /home
  controller: App\Controller\MemeController::home

top10:
  path: /top10
  controller: App\Controller\MemeController::top10

user:
  path: /users
  controller: App\Controller\UserController::index

add:
  path: /add
  controller: App\Controller\MemeController::add

